// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Camera struct {
	ID      string `json:"id"`
	PlaceID string `json:"placeID"`
	UserID  string `json:"userID"`
}

type GetCamerasCriteria struct {
	PlaceID *string `json:"placeID,omitempty"`
}

type GetPlacesCriteria struct {
	UserID *string `json:"userID,omitempty"`
}

type Place struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	UserID  string    `json:"userID"`
	Cameras []*Camera `json:"cameras"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}
